/**
 * E2EE — Group Crypto
 *
 * Group messages use a single shared AES-256-GCM key per group ("group key").
 * This key is generated by the group creator, then wrapped (encrypted)
 * individually for each member using ECDH key agreement:
 *
 *   For each member:
 *     1. ECDH(myPrivate, memberPublic)  → sharedBits
 *     2. HKDF(sharedBits, salt=groupId, info="chatapp-group-wrap-v1") → wrapKey (AES-256-GCM)
 *     3. AES-GCM-encrypt(rawGroupKey, wrapKey, randomIV) → wrappedKey blob
 *     4. Upload wrappedKey to server for that member.
 *
 * Any member who wants to send/receive messages:
 *     1. GET their own wrappedKey blob from the server.
 *     2. ECDH(myPrivate, wrappedByPublic) → sharedBits → wrapKey
 *     3. AES-GCM-decrypt(wrappedKey) → raw group key bytes
 *     4. Import as AES-256-GCM key, cache in IndexedDB as "groupKey:<groupId>".
 *
 * Message encryption is identical to 1:1 — AES-256-GCM with a random IV,
 * serialised as base64(JSON({ ciphertext, iv })).
 *
 * Key rotation when a member is removed is out of scope for v1.
 * TODO(v2): generate a new group key on membership change, re-wrap for
 * remaining members, and bump a keyVersion field in WrappedGroupKey.
 */

import { idbGet, idbSet } from './idbStore';
import { getOwnPrivateKey, fetchPeerPublicKey } from './keyManager';
import { API_URL } from '../config/api';

const AES_PARAMS      = { name: 'AES-GCM', length: 256 };
const WRAP_HKDF_INFO  = new TextEncoder().encode('chatapp-group-wrap-v1');
const IV_LENGTH       = 12;

// ---- Helpers ----------------------------------------------------------------

function bufferToBase64(buffer) {
  return btoa(String.fromCharCode(...new Uint8Array(buffer)));
}

function base64ToBuffer(b64) {
  const bin = atob(b64);
  const buf = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) buf[i] = bin.charCodeAt(i);
  return buf.buffer;
}

/**
 * Derive a one-time wrap/unwrap AES key from an ECDH shared secret.
 * Both the sender (who wraps) and the recipient (who unwraps) independently
 * derive the same key, so no wrap key is ever stored or transmitted.
 */
async function deriveWrapKey(myPrivateKey, peerPublicKey, groupId) {
  const sharedBits = await crypto.subtle.deriveBits(
    { name: 'ECDH', public: peerPublicKey },
    myPrivateKey,
    256,
  );
  const hkdfKey = await crypto.subtle.importKey(
    'raw', sharedBits, { name: 'HKDF' }, false, ['deriveKey'],
  );
  const salt = new TextEncoder().encode(groupId);
  return crypto.subtle.deriveKey(
    { name: 'HKDF', hash: 'SHA-256', salt, info: WRAP_HKDF_INFO },
    hkdfKey,
    AES_PARAMS,
    false,
    ['encrypt', 'decrypt'],
  );
}

// ---- Group key generation & distribution ------------------------------------

/**
 * Generate a fresh group AES key and wrap it for every group member.
 * Called once by the group creator immediately after the group is created,
 * and again whenever a new member is added (for the new member only).
 *
 * @param {string}   groupId
 * @param {string[]} memberUserIds   — all member userIds (including self)
 * @param {string}   myUserId        — the caller's userId
 * @param {string}   token           — JWT
 * @returns {Promise<CryptoKey>}     the raw group key (already cached in IDB)
 */
export async function generateAndDistributeGroupKey(groupId, memberUserIds, myUserId, token) {
  // 1. Generate a random AES-256-GCM group key (extractable so we can wrap it).
  const groupKey = await crypto.subtle.generateKey(AES_PARAMS, true, ['encrypt', 'decrypt']);
  const rawGroupKey = await crypto.subtle.exportKey('raw', groupKey);

  const myPrivateKey = await getOwnPrivateKey();
  if (!myPrivateKey) throw new Error('E2EE: own private key not found');

  // 2. Wrap the raw group key for each member (including self).
  const wrappedKeys = [];
  for (const memberId of memberUserIds) {
    try {
      let peerPublicKey;
      if (memberId === myUserId) {
        // Wrap for self: use own public key (already imported from idbStore at top).
        peerPublicKey = await idbGet('identity:publicKey');
        if (!peerPublicKey) continue;
      } else {
        peerPublicKey = await fetchPeerPublicKey(memberId, token);
      }

      const wrapKey  = await deriveWrapKey(myPrivateKey, peerPublicKey, groupId);
      const iv       = crypto.getRandomValues(new Uint8Array(IV_LENGTH));
      const wrapped  = await crypto.subtle.encrypt({ name: 'AES-GCM', iv }, wrapKey, rawGroupKey);

      wrappedKeys.push({
        userId: memberId,
        wrappedKey: btoa(JSON.stringify({
          ciphertext: bufferToBase64(wrapped),
          iv: bufferToBase64(iv),
        })),
      });
    } catch {
      // If a member hasn't uploaded their public key yet, skip them.
      // They will receive the wrapped key when they next join and trigger a re-wrap.
    }
  }

  // 3. Upload all wrapped keys to the server in one batch request.
  if (wrappedKeys.length) {
    await fetch(`${API_URL}/api/keys/groups/${groupId}/wrapped-keys`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        Authorization: `Bearer ${token}`,
      },
      body: JSON.stringify({ keys: wrappedKeys }),
    });
  }

  // 4. Cache the non-extractable version in IndexedDB for immediate use.
  const nonExtractable = await crypto.subtle.importKey('raw', rawGroupKey, AES_PARAMS, false, ['encrypt', 'decrypt']);
  await idbSet(`groupKey:${groupId}`, nonExtractable);
  return nonExtractable;
}

// ---- Group key retrieval (unwrap) -------------------------------------------

/**
 * Fetch and unwrap the group key for the calling user, then cache it.
 * Returns the cached key if already in IndexedDB.
 *
 * @param {string} groupId
 * @param {string} myUserId
 * @param {string} token
 * @returns {Promise<CryptoKey>}
 * @throws if the server has no wrapped key for this user yet
 */
export async function getOrFetchGroupKey(groupId, myUserId, token) {
  const idbKey = `groupKey:${groupId}`;
  const cached = await idbGet(idbKey);
  if (cached) return cached;

  // Fetch the wrapped blob from the server.
  const res = await fetch(`${API_URL}/api/keys/groups/${groupId}/wrapped-key`, {
    headers: { Authorization: `Bearer ${token}` },
  });

  // 404 means no key has been distributed for this group yet.
  // This happens for groups created before E2EE was added, or when key
  // distribution failed at creation time. Fetch the group members from the
  // server and generate+distribute the key now (self-healing).
  if (res.status === 404) {
    const groupRes = await fetch(`${API_URL}/api/groups`, {
      headers: { Authorization: `Bearer ${token}` },
    });
    if (!groupRes.ok) throw new Error(`No wrapped group key for group ${groupId}`);
    const groups = await groupRes.json();
    const group = groups.find((g) => g.id === groupId);
    if (!group) throw new Error(`No wrapped group key for group ${groupId}`);
    const memberIds = (group.members || []).map((m) => m.userId);
    return generateAndDistributeGroupKey(groupId, memberIds, myUserId, token);
  }

  if (!res.ok) throw new Error(`No wrapped group key for group ${groupId}`);

  const { wrappedKey: wrappedB64, wrappedBy } = await res.json();

  // Derive the wrap key using our private key + the wrapper's public key.
  const myPrivateKey    = await getOwnPrivateKey();
  const wrapperPublicKey = await fetchPeerPublicKey(wrappedBy, token);
  if (!myPrivateKey) throw new Error('E2EE: own private key not found');

  const wrapKey = await deriveWrapKey(myPrivateKey, wrapperPublicKey, groupId);

  const { ciphertext, iv } = JSON.parse(atob(wrappedB64));
  const rawGroupKey = await crypto.subtle.decrypt(
    { name: 'AES-GCM', iv: base64ToBuffer(iv) },
    wrapKey,
    base64ToBuffer(ciphertext),
  );

  const groupKey = await crypto.subtle.importKey('raw', rawGroupKey, AES_PARAMS, false, ['encrypt', 'decrypt']);
  await idbSet(idbKey, groupKey);
  return groupKey;
}

// ---- Encrypt ----------------------------------------------------------------

/**
 * Encrypt a plaintext string with the group's AES key.
 *
 * @param {string} groupId
 * @param {string} myUserId
 * @param {string} plaintext
 * @param {string} token
 * @returns {Promise<string>}  base64-encoded JSON payload { ciphertext, iv }
 */
export async function encryptGroup(groupId, myUserId, plaintext, token) {
  const groupKey = await getOrFetchGroupKey(groupId, myUserId, token);
  const iv       = crypto.getRandomValues(new Uint8Array(IV_LENGTH));
  const encoded  = new TextEncoder().encode(plaintext);

  const ciphertextBuffer = await crypto.subtle.encrypt(
    { name: 'AES-GCM', iv },
    groupKey,
    encoded,
  );

  return btoa(JSON.stringify({
    ciphertext: bufferToBase64(ciphertextBuffer),
    iv: bufferToBase64(iv),
  }));
}

// ---- Decrypt ----------------------------------------------------------------

/**
 * Decrypt a ciphertext payload with the group's AES key.
 *
 * @param {string} groupId
 * @param {string} myUserId
 * @param {string} payloadB64
 * @param {string} token
 * @returns {Promise<string>}  plaintext
 */
export async function decryptGroup(groupId, myUserId, payloadB64, token) {
  const groupKey = await getOrFetchGroupKey(groupId, myUserId, token);
  const { ciphertext, iv } = JSON.parse(atob(payloadB64));

  const plainBuffer = await crypto.subtle.decrypt(
    { name: 'AES-GCM', iv: base64ToBuffer(iv) },
    groupKey,
    base64ToBuffer(ciphertext),
  );

  return new TextDecoder().decode(plainBuffer);
}
